<?xml version="1.0" encoding="UTF-8" ?>
<testsuite 
errors="0" failures="20" hostname="localhost.localdomain" name="ScalaArray1Suite" tests="27" time="0.042" timestamp="2014-08-11T21:44:08">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment">
    </property>
    <property 
    name="sun.boot.library.path" value="/usr/java/jdk1.7.0_25/jre/lib/amd64">
</property>
    <property name="java.vm.version" value="23.25-b01"> </property>
    <property name="java.vm.vendor" value="Oracle Corporation"> </property>
    <property name="java.vendor.url" value="http://java.oracle.com/">
    </property>
    <property name="path.separator" value=":"> </property>
    <property name="java.vm.name" value="Java HotSpot(TM) 64-Bit Server VM">
    </property>
    <property name="file.encoding.pkg" value="sun.io"> </property>
    <property name="user.country" value="US"> </property>
    <property name="sun.java.launcher" value="SUN_STANDARD"> </property>
    <property name="sun.os.patch.level" value="unknown"> </property>
    <property 
    name="java.vm.specification.name" value="Java Virtual Machine Specification">
</property>
    <property name="user.dir" value="/home/dc/scalaodersky/TestScalatest">
    </property>
    <property name="java.runtime.version" value="1.7.0_25-b15"> </property>
    <property 
    name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment">
</property>
    <property name="basedir" value="/home/dc/scalaodersky/TestScalatest">
    </property>
    <property 
    name="java.endorsed.dirs" value="/usr/java/jdk1.7.0_25/jre/lib/endorsed">
</property>
    <property name="os.arch" value="amd64"> </property>
    <property name="java.io.tmpdir" value="/tmp"> </property>
    <property name="line.separator" value=" "> </property>
    <property name="java.vm.specification.vendor" value="Oracle Corporation">
    </property>
    <property name="os.name" value="Linux"> </property>
    <property name="sun.jnu.encoding" value="UTF-8"> </property>
    <property 
    name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib">
</property>
    <property 
    name="java.specification.name" value="Java Platform API Specification">
</property>
    <property name="java.class.version" value="51.0"> </property>
    <property 
    name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers">
</property>
    <property name="os.version" value="2.6.32-431.20.3.el6.x86_64"> </property>
    <property name="user.home" value="/home/dc"> </property>
    <property name="user.timezone" value=""> </property>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob">
    </property>
    <property name="file.encoding" value="UTF-8"> </property>
    <property name="java.specification.version" value="1.7"> </property>
    <property name="user.name" value="dc"> </property>
    <property 
    name="java.class.path" value="/home/dc/scalaodersky/TestScalatest/target/test-classes:/home/dc/scalaodersky/TestScalatest/target/classes:/home/dc/.m2/repository/junit/junit/3.8.1/junit-3.8.1.jar:/home/dc/.m2/repository/org/scala-lang/scala-library/2.10.0/scala-library-2.10.0.jar:/home/dc/.m2/repository/org/scalatest/scalatest_2.10/2.0.M5b/scalatest_2.10-2.0.M5b.jar">
</property>
    <property name="java.vm.specification.version" value="1.7"> </property>
    <property name="sun.arch.data.model" value="64"> </property>
    <property name="java.home" value="/usr/java/jdk1.7.0_25/jre"> </property>
    <property 
    name="sun.java.command" value="org.scalatest.tools.Runner -R /home/dc/scalaodersky/TestScalatest/target/classes /home/dc/scalaodersky/TestScalatest/target/test-classes -o -f /home/dc/scalaodersky/codingbat/surefire-reports/TestSuite.txt -u /home/dc/scalaodersky/codingbat/surefire-reports/.">
</property>
    <property name="java.specification.vendor" value="Oracle Corporation">
    </property>
    <property name="user.language" value="en"> </property>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"> </property>
    <property name="java.vm.info" value="mixed mode"> </property>
    <property name="java.version" value="1.7.0_25"> </property>
    <property 
    name="java.ext.dirs" value="/usr/java/jdk1.7.0_25/jre/lib/ext:/usr/java/packages/lib/ext">
</property>
    <property 
    name="sun.boot.class.path" value="/usr/java/jdk1.7.0_25/jre/lib/resources.jar:/usr/java/jdk1.7.0_25/jre/lib/rt.jar:/usr/java/jdk1.7.0_25/jre/lib/sunrsasign.jar:/usr/java/jdk1.7.0_25/jre/lib/jsse.jar:/usr/java/jdk1.7.0_25/jre/lib/jce.jar:/usr/java/jdk1.7.0_25/jre/lib/charsets.jar:/usr/java/jdk1.7.0_25/jre/lib/jfr.jar:/usr/java/jdk1.7.0_25/jre/classes">
</property>
    <property name="java.vendor" value="Oracle Corporation"> </property>
    <property name="file.separator" value="/"> </property>
    <property 
    name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/">
</property>
    <property name="sun.cpu.endian" value="little"> </property>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"> </property>
    <property name="sun.desktop" value="gnome"> </property>
    <property name="sun.cpu.isalist" value=""> </property>
  </properties>
  <testcase 
  name="testing firstLast6" classname="ScalaArray1Suite" time="0.0">
</testcase>
  <testcase 
  name="testing sameFirstLast" classname="ScalaArray1Suite" time="0.0">
</testcase>
  <testcase name="testing makePi" classname="ScalaArray1Suite" time="0.005">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$3.apply$mcV$sp(ScalaArray1Suite.scala:41)
      at ScalaArray1Suite$$anonfun$3.apply(ScalaArray1Suite.scala:41)
      at ScalaArray1Suite$$anonfun$3.apply(ScalaArray1Suite.scala:41)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase 
  name="testing commonEnd" classname="ScalaArray1Suite" time="0.001">
</testcase>
  <testcase name="testing sum3" classname="ScalaArray1Suite" time="0.002">
  </testcase>
  <testcase 
  name="testing rotateLeft3" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$6.apply$mcV$sp(ScalaArray1Suite.scala:77)
      at ScalaArray1Suite$$anonfun$6.apply(ScalaArray1Suite.scala:76)
      at ScalaArray1Suite$$anonfun$6.apply(ScalaArray1Suite.scala:76)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase name="testing reverse3" classname="ScalaArray1Suite" time="0.0">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$7.apply$mcV$sp(ScalaArray1Suite.scala:91)
      at ScalaArray1Suite$$anonfun$7.apply(ScalaArray1Suite.scala:90)
      at ScalaArray1Suite$$anonfun$7.apply(ScalaArray1Suite.scala:90)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing maxEnd3" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$8.apply$mcV$sp(ScalaArray1Suite.scala:104)
      at ScalaArray1Suite$$anonfun$8.apply(ScalaArray1Suite.scala:103)
      at ScalaArray1Suite$$anonfun$8.apply(ScalaArray1Suite.scala:103)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing sum2" classname="ScalaArray1Suite" time="0.005">
  </testcase>
  <testcase 
  name="testing middleWay" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$10.apply$mcV$sp(ScalaArray1Suite.scala:127)
      at ScalaArray1Suite$$anonfun$10.apply(ScalaArray1Suite.scala:127)
      at ScalaArray1Suite$$anonfun$10.apply(ScalaArray1Suite.scala:127)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase 
  name="testing makeEnds" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$11.apply$mcV$sp(ScalaArray1Suite.scala:143)
      at ScalaArray1Suite$$anonfun$11.apply(ScalaArray1Suite.scala:142)
      at ScalaArray1Suite$$anonfun$11.apply(ScalaArray1Suite.scala:142)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase name="testing has23" classname="ScalaArray1Suite" time="0.001">
  </testcase>
  <testcase name="testing no23" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$13.apply$mcV$sp(ScalaArray1Suite.scala:168)
      at ScalaArray1Suite$$anonfun$13.apply(ScalaArray1Suite.scala:167)
      at ScalaArray1Suite$$anonfun$13.apply(ScalaArray1Suite.scala:167)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase 
  name="testing makeLast" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$14.apply$mcV$sp(ScalaArray1Suite.scala:182)
      at ScalaArray1Suite$$anonfun$14.apply(ScalaArray1Suite.scala:181)
      at ScalaArray1Suite$$anonfun$14.apply(ScalaArray1Suite.scala:181)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase 
  name="testing double23" classname="ScalaArray1Suite" time="0.001">
</testcase>
  <testcase name="testing fix23" classname="ScalaArray1Suite" time="0.0">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$16.apply$mcV$sp(ScalaArray1Suite.scala:231)
      at ScalaArray1Suite$$anonfun$16.apply(ScalaArray1Suite.scala:230)
      at ScalaArray1Suite$$anonfun$16.apply(ScalaArray1Suite.scala:230)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing start1" classname="ScalaArray1Suite" time="0.001">
    <failure message="0" type="class java.lang.ArrayIndexOutOfBoundsException">
      java.lang.ArrayIndexOutOfBoundsException: 0
      at edu.stanford.codingbat.ScalaArray1$$anonfun$start1$1.apply(ScalaArray1.scala:256)
      at edu.stanford.codingbat.ScalaArray1$$anonfun$start1$1.apply(ScalaArray1.scala:256)
      at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:114)
      at scala.collection.TraversableOnce$$anonfun$count$1.apply(TraversableOnce.scala:113)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at scala.collection.TraversableOnce$class.count(TraversableOnce.scala:113)
      at scala.collection.AbstractTraversable.count(Traversable.scala:105)
      at edu.stanford.codingbat.ScalaArray1.start1(ScalaArray1.scala:256)
      at ScalaArray1Suite$$anonfun$17.apply$mcV$sp(ScalaArray1Suite.scala:248)
      at ScalaArray1Suite$$anonfun$17.apply(ScalaArray1Suite.scala:245)
      at ScalaArray1Suite$$anonfun$17.apply(ScalaArray1Suite.scala:245)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
    </failure>
  </testcase>
  <testcase 
  name="testing biggerTwo" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$18.apply$mcV$sp(ScalaArray1Suite.scala:259)
      at ScalaArray1Suite$$anonfun$18.apply(ScalaArray1Suite.scala:258)
      at ScalaArray1Suite$$anonfun$18.apply(ScalaArray1Suite.scala:258)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase 
  name="testing makeMiddle" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$19.apply$mcV$sp(ScalaArray1Suite.scala:273)
      at ScalaArray1Suite$$anonfun$19.apply(ScalaArray1Suite.scala:272)
      at ScalaArray1Suite$$anonfun$19.apply(ScalaArray1Suite.scala:272)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase name="testing plusTwo" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$20.apply$mcV$sp(ScalaArray1Suite.scala:285)
      at ScalaArray1Suite$$anonfun$20.apply(ScalaArray1Suite.scala:284)
      at ScalaArray1Suite$$anonfun$20.apply(ScalaArray1Suite.scala:284)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase 
  name="testing swapEnds" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$21.apply$mcV$sp(ScalaArray1Suite.scala:299)
      at ScalaArray1Suite$$anonfun$21.apply(ScalaArray1Suite.scala:297)
      at ScalaArray1Suite$$anonfun$21.apply(ScalaArray1Suite.scala:297)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase name="testing midThree" classname="ScalaArray1Suite" time="0.0">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$22.apply$mcV$sp(ScalaArray1Suite.scala:312)
      at ScalaArray1Suite$$anonfun$22.apply(ScalaArray1Suite.scala:311)
      at ScalaArray1Suite$$anonfun$22.apply(ScalaArray1Suite.scala:311)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing maxTriple" classname="ScalaArray1Suite" time="0.0">
    <failure message="3" type="class java.lang.ArrayIndexOutOfBoundsException">
      java.lang.ArrayIndexOutOfBoundsException: 3
      at edu.stanford.codingbat.ScalaArray1.maxTriple(ScalaArray1.scala:326)
      at ScalaArray1Suite$$anonfun$23.apply$mcV$sp(ScalaArray1Suite.scala:326)
      at ScalaArray1Suite$$anonfun$23.apply(ScalaArray1Suite.scala:325)
      at ScalaArray1Suite$$anonfun$23.apply(ScalaArray1Suite.scala:325)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
    </failure>
  </testcase>
  <testcase 
  name="testing frontPiece" classname="ScalaArray1Suite" time="0.0">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$24.apply$mcV$sp(ScalaArray1Suite.scala:338)
      at ScalaArray1Suite$$anonfun$24.apply(ScalaArray1Suite.scala:337)
      at ScalaArray1Suite$$anonfun$24.apply(ScalaArray1Suite.scala:337)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
</testcase>
  <testcase name="testing unlucky1" classname="ScalaArray1Suite" time="0.0">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$25.apply$mcV$sp(ScalaArray1Suite.scala:351)
      at ScalaArray1Suite$$anonfun$25.apply(ScalaArray1Suite.scala:350)
      at ScalaArray1Suite$$anonfun$25.apply(ScalaArray1Suite.scala:350)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing make2" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$26.apply$mcV$sp(ScalaArray1Suite.scala:363)
      at ScalaArray1Suite$$anonfun$26.apply(ScalaArray1Suite.scala:362)
      at ScalaArray1Suite$$anonfun$26.apply(ScalaArray1Suite.scala:362)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <testcase name="testing front11" classname="ScalaArray1Suite" time="0.001">
    <failure 
    message="org.scalatest.exceptions.TestFailedException was thrown." type="class org.scalatest.exceptions.TestFailedException">
      org.scalatest.exceptions.TestFailedException
      at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:391)
      at ScalaArray1Suite.newAssertionFailedException(ScalaArray1Suite.scala:9)
      at org.scalatest.Assertions$class.assert(Assertions.scala:386)
      at ScalaArray1Suite.assert(ScalaArray1Suite.scala:9)
      at ScalaArray1Suite$$anonfun$27.apply$mcV$sp(ScalaArray1Suite.scala:376)
      at ScalaArray1Suite$$anonfun$27.apply(ScalaArray1Suite.scala:375)
      at ScalaArray1Suite$$anonfun$27.apply(ScalaArray1Suite.scala:375)
      at org.scalatest.FunSuite$$anon$1.apply(FunSuite.scala:1465)
      at org.scalatest.Suite$class.withFixture(Suite.scala:1099)
      at ScalaArray1Suite.withFixture(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$class.invokeWithFixture$1(FunSuite.scala:1462)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.FunSuite$$anonfun$runTest$1.apply(FunSuite.scala:1474)
      at org.scalatest.SuperEngine.runTestImpl(Engine.scala:234)
      at org.scalatest.FunSuite$class.runTest(FunSuite.scala:1474)
      at ScalaArray1Suite.runTest(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.FunSuite$$anonfun$runTests$1.apply(FunSuite.scala:1506)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:330)
      at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:318)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:318)
      at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:313)
      at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:394)
      at org.scalatest.FunSuite$class.runTests(FunSuite.scala:1506)
      at ScalaArray1Suite.runTests(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.run(Suite.scala:1426)
      at ScalaArray1Suite.org$scalatest$FunSuite$$super$run(ScalaArray1Suite.scala:9)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.FunSuite$$anonfun$run$1.apply(FunSuite.scala:1510)
      at org.scalatest.SuperEngine.runImpl(Engine.scala:430)
      at org.scalatest.FunSuite$class.run(FunSuite.scala:1510)
      at ScalaArray1Suite.run(ScalaArray1Suite.scala:9)
      at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1507)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1543)
      at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1541)
      at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
      at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:105)
      at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1541)
      at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:29)
      at org.scalatest.Suite$class.run(Suite.scala:1423)
      at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:29)
      at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2180)
      at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2174)
      at scala.collection.immutable.List.foreach(List.scala:309)
      at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2174)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:850)
      at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:849)
      at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2221)
      at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:848)
      at org.scalatest.tools.Runner$.main(Runner.scala:686)
      at org.scalatest.tools.Runner.main(Runner.scala)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
